name: MedicationApp
options:
  bundleIdPrefix: com.example
settings:
  base:
    SWIFT_VERSION: 6.2
    IPHONEOS_DEPLOYMENT_TARGET: 26.0
packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
targets:
  MedicationApp:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Features
      - path: Shared
      - path: Networking
      - path: Services
      - path: Assets.xcassets
      - path: Resources
      - path: GoogleService-Info.plist
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseMessaging
    info:
      path: App/Info.plist
      properties:
        API_BASE_URL: "https://med-manager-v3.vercel.app/"
        SUPABASE_URL: "https://kairaeahklftpjfcaddh.supabase.co"
        SUPABASE_ANON_KEY: "sb_publishable_nVf6RMV1tUkg8ew7BJLVnw_YDnUMRra"
        CFBundleDisplayName: "お薬管理アプリ"
        UILaunchStoryboardName: "LaunchScreen"
        UIBackgroundModes:
          - remote-notification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.med-manager-app
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
    scheme:
      storeKitConfiguration: App/Products.storekit
      testTargets:
        - MedicationAppTests
  MedicationAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    info:
      path: Tests/Info.plist
    dependencies:
      - target: MedicationApp
