ALTER TABLE "Patient"
  ADD COLUMN "morningTime" TEXT NOT NULL DEFAULT '08:00',
  ADD COLUMN "noonTime" TEXT NOT NULL DEFAULT '13:00',
  ADD COLUMN "eveningTime" TEXT NOT NULL DEFAULT '19:00',
  ADD COLUMN "bedtimeTime" TEXT NOT NULL DEFAULT '22:00';
