-- The app accesses application tables through the API server's database
-- connection, not through Supabase PostgREST. Do not expose public tables to
-- anon/authenticated clients.
REVOKE ALL ON SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM anon, authenticated;

ALTER TABLE "CaregiverEntitlement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaregiverPatientLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DoseRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DoseRecordEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryAlertEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LinkingAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LinkingCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Medication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MedicationInventoryAdjustment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Patient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PatientSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PatientSlotTimeRevision" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PushDelivery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PushDevice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Regimen" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "prn_dose_records" ENABLE ROW LEVEL SECURITY;
